### ISSUE TITLE
using try and catch out of scope

### ISSUE THREAD

**Issue by carmeloevoli** [sghislandi/GSSI_Numerical_Methods_2020-2021#2]
https://github.com/sghislandi/GSSI_Numerical_Methods_2020-2021/blob/86aaface114661ff350b127a5bd1a004868d6b7a/pyplots/simpson_integration/error_plotter.py#L6

please don't use `try` and `catch` here, but rather `if(file_exist(...)):`

**Comment by sghislandi** [comment]
Thank you for the suggestion, I have replaced it
